name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: somehow e2e fails on Linux and Windows, disabled for now
        os: [ubuntu-latest, window-latest, macos-latest]
        # os: [macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      # - name: Linux Setup
      #   if: ${{ matrix.os == 'ubuntu-latest' }}
      #   run: |
      #     sudo apt-get install xvfb
      #     export DISPLAY=:99.0
      #     Xvfb -ac :99 -screen 0 1920x1080x16
      #   env:
      #     CI: true

      - name: Install
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Unit Tests
        run: yarn test:unit
        env:
          CI: true

      - run: xvfb-run -a yarn run test:e2e
        if: runner.os == 'Linux'

      - run: yarn run test:e2e
        if: runner.os != 'Linux'
